name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "* * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # repositories: 300
          # repositories_forks: yes
          # commits_authoring: simon@joyful.com
          # plugin_achievements: yes
          # plugin_notable: yes
          #plugin_achievements_limit: 10
          #plugin_achievements_ignored: gister, chatter
          
